import { store } from 'lib/reducers'

const selectedLanguage = store.getState().language.name

export const RoutePath = {
	root: '/',
	home: `/${selectedLanguage}/`,
	movies: `/${selectedLanguage}/movies`,
	login: `/${selectedLanguage}/login`,
	signUp: `/${selectedLanguage}/signup`,
	registration: `/${selectedLanguage}/signup/registration`,
	registrationForm: `/${selectedLanguage}/signup/regform`,
	registationPassword: `/${selectedLanguage}/signup/password`,
	choosePlan: `/${selectedLanguage}/signup/choose-plan`,
	planForm: `/${selectedLanguage}/signup/planform`,
	payment: `/${selectedLanguage}/signup/payment`,
	paymentSuccess: `/${selectedLanguage}/signup/payment/success`,
	loginOut: `/${selectedLanguage}/loginout`,
	loginHelp: `/${selectedLanguage}/LoginHelp`,
	profile: '/profile',
	user: '/user',
	userDetail: '/user/:id',
	userEdit: '/user/:id/edit',
	userDelete: '/user/:id/delete',
	userCreate: '/user/create',
	faq: '/faq',
	account: '/account',
	investor: '/inventory-relations',
	redeemGiftCard: '/redeem-gift-card',
	waysToWatch: '/ways-to-watch',
	privacy: '/privacy',
	corporateInfo: '/corporate-information',
	speedTest: '/speed-test',
	legalNotices: '/legal-notices',
	helpCenter: '/help-center',
	mediaCenter: '/media-center',
	jobs: '/jobs',
	buyGiftCard: '/buy-gift-card',
	termsOfUse: '/terms-of-use',
	cookiePreferences: '/cookie-preferences',
	contactUs: '/contact-us',
	legalGuarantee: '/legal-guarantee',
	onlyOnNetflix: '/only-on-netflix',
}
